export interface Template {
  id: string
  name: string
  category: "quote" | "marketing" | "educational" | "minimal" | "colorful" | "corporate" | "neon" | "elegant"
  backgroundType: "gradient" | "solid"
  gradient?: string
  backgroundColor?: string
  borderColor?: string
  borderWidth?: number
  textColor: string
  accentColor?: string
  fontFamily: string
  fontWeight?: number
  fontSize: number
  textAlign: "left" | "center" | "right"
  padding: number
  preview?: string
  isPremium?: boolean
}

export const templates: Template[] = [
  {
    id: "visionary-1",
    name: "Visionary Neon",
    category: "neon",
    backgroundType: "solid",
    backgroundColor: "#0A1A2F",
    borderColor: "#0FB4FF",
    borderWidth: 4,
    textColor: "#ffffff",
    accentColor: "#0FB4FF",
    fontFamily: "Inter",
    fontWeight: 300,
    fontSize: 32,
    textAlign: "center",
    padding: 50,
    preview: "On ne change pas un pays avec du bruit. On le change avec des systèmes.",
  },
  {
    id: "visionary-2",
    name: "Neon Purple",
    category: "neon",
    backgroundType: "solid",
    backgroundColor: "#1A0A2F",
    borderColor: "#A855F7",
    borderWidth: 4,
    textColor: "#ffffff",
    accentColor: "#A855F7",
    fontFamily: "Inter",
    fontWeight: 300,
    fontSize: 32,
    textAlign: "center",
    padding: 50,
    preview: "Innovation distinguishes between a leader and a follower.",
    isPremium: true,
  },
  {
    id: "visionary-3",
    name: "Neon Green",
    category: "neon",
    backgroundType: "solid",
    backgroundColor: "#0A1F1A",
    borderColor: "#10B981",
    borderWidth: 4,
    textColor: "#ffffff",
    accentColor: "#10B981",
    fontFamily: "Inter",
    fontWeight: 300,
    fontSize: 32,
    textAlign: "center",
    padding: 50,
    preview: "The future belongs to those who believe.",
  },
  {
    id: "visionary-4",
    name: "Neon Red",
    category: "neon",
    backgroundType: "solid",
    backgroundColor: "#1F0A0A",
    borderColor: "#EF4444",
    borderWidth: 4,
    textColor: "#ffffff",
    accentColor: "#EF4444",
    fontFamily: "Inter",
    fontWeight: 300,
    fontSize: 32,
    textAlign: "center",
    padding: 50,
    preview: "Action is the foundational key to all success.",
    isPremium: true,
  },
  {
    id: "elegant-1",
    name: "Elegant Black",
    category: "elegant",
    backgroundType: "solid",
    backgroundColor: "#000000",
    borderColor: "#D4AF37",
    borderWidth: 3,
    textColor: "#ffffff",
    accentColor: "#D4AF37",
    fontFamily: "Playfair Display",
    fontWeight: 400,
    fontSize: 30,
    textAlign: "center",
    padding: 60,
    preview: "Excellence is not a destination but a continuous journey.",
    isPremium: true,
  },
  {
    id: "elegant-2",
    name: "Elegant White",
    category: "elegant",
    backgroundType: "solid",
    backgroundColor: "#FAFAFA",
    borderColor: "#1F2937",
    borderWidth: 2,
    textColor: "#1F2937",
    accentColor: "#6B7280",
    fontFamily: "Playfair Display",
    fontWeight: 400,
    fontSize: 30,
    textAlign: "center",
    padding: 60,
    preview: "Simplicity is the ultimate sophistication.",
  },
  // Original gradient templates with updated interface
  {
    id: "motivational-1",
    name: "Motivational Gradient",
    category: "quote",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    textColor: "#ffffff",
    fontFamily: "Playfair Display",
    fontSize: 32,
    textAlign: "center",
    padding: 40,
    preview: "Dream big, start small, act now.",
  },
  {
    id: "business-1",
    name: "Business Blue",
    category: "marketing",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 28,
    textAlign: "center",
    padding: 40,
    preview: "Grow your business today",
  },
  {
    id: "education-1",
    name: "Education Teal",
    category: "educational",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #0d9488 0%, #14b8a6 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 26,
    textAlign: "left",
    padding: 40,
    preview: "Did you know?",
  },
  {
    id: "minimal-1",
    name: "Minimal Dark",
    category: "minimal",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #1f2937 0%, #111827 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 28,
    textAlign: "center",
    padding: 50,
    preview: "Less is more.",
  },
  {
    id: "colorful-1",
    name: "Sunset Vibes",
    category: "colorful",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #f97316 0%, #ec4899 100%)",
    textColor: "#ffffff",
    fontFamily: "Poppins",
    fontSize: 30,
    textAlign: "center",
    padding: 40,
    preview: "Make it pop!",
  },
  {
    id: "corporate-1",
    name: "Corporate Gray",
    category: "corporate",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #374151 0%, #4b5563 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 26,
    textAlign: "left",
    padding: 40,
    preview: "Professional Excellence",
  },
  {
    id: "quote-2",
    name: "Ocean Blue",
    category: "quote",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #0ea5e9 0%, #2dd4bf 100%)",
    textColor: "#ffffff",
    fontFamily: "Playfair Display",
    fontSize: 30,
    textAlign: "center",
    padding: 45,
    preview: "Stay focused, stay positive",
  },
  {
    id: "marketing-2",
    name: "Bold Red",
    category: "marketing",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #dc2626 0%, #f97316 100%)",
    textColor: "#ffffff",
    fontFamily: "Poppins",
    fontSize: 32,
    textAlign: "center",
    padding: 35,
    preview: "Limited Time Offer!",
  },
  {
    id: "quote-3",
    name: "Royal Purple",
    category: "quote",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #c026d3 100%)",
    textColor: "#ffffff",
    fontFamily: "Playfair Display",
    fontSize: 32,
    textAlign: "center",
    padding: 45,
    preview: "Believe in yourself",
    isPremium: true,
  },
  {
    id: "minimal-2",
    name: "Pure White",
    category: "minimal",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #ffffff 0%, #f3f4f6 100%)",
    textColor: "#111827",
    fontFamily: "Inter",
    fontSize: 28,
    textAlign: "center",
    padding: 50,
    preview: "Simplicity wins.",
  },
  {
    id: "colorful-2",
    name: "Neon Pop",
    category: "colorful",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #06b6d4 0%, #8b5cf6 100%)",
    textColor: "#ffffff",
    fontFamily: "Poppins",
    fontSize: 30,
    textAlign: "center",
    padding: 40,
    preview: "Stand out!",
    isPremium: true,
  },
  {
    id: "educational-2",
    name: "Fresh Green",
    category: "educational",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #22c55e 0%, #16a34a 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 26,
    textAlign: "center",
    padding: 40,
    preview: "Learn something new",
  },
  {
    id: "marketing-3",
    name: "Golden Hour",
    category: "marketing",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #fbbf24 0%, #f97316 100%)",
    textColor: "#1f2937",
    fontFamily: "Poppins",
    fontSize: 30,
    textAlign: "center",
    padding: 40,
    preview: "Exclusive Deal",
    isPremium: true,
  },
  {
    id: "corporate-2",
    name: "Navy Pro",
    category: "corporate",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #1e3a8a 0%, #1e40af 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 26,
    textAlign: "center",
    padding: 40,
    preview: "Leading the way",
  },
  {
    id: "quote-4",
    name: "Warm Blush",
    category: "quote",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #fda4af 0%, #fb7185 100%)",
    textColor: "#1f2937",
    fontFamily: "Playfair Display",
    fontSize: 30,
    textAlign: "center",
    padding: 45,
    preview: "Love what you do",
  },
  {
    id: "minimal-3",
    name: "Soft Gray",
    category: "minimal",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #e5e7eb 0%, #d1d5db 100%)",
    textColor: "#374151",
    fontFamily: "Inter",
    fontSize: 28,
    textAlign: "center",
    padding: 50,
    preview: "Keep it simple",
  },
]

export const platformSizes = {
  "instagram-square": { width: 1080, height: 1080, label: "Instagram Post" },
  "instagram-story": { width: 1080, height: 1920, label: "Instagram Story" },
  tiktok: { width: 1080, height: 1920, label: "TikTok" },
  facebook: { width: 1200, height: 630, label: "Facebook Post" },
  twitter: { width: 1200, height: 675, label: "X/Twitter" },
  linkedin: { width: 1200, height: 627, label: "LinkedIn" },
}

export type PlatformKey = keyof typeof platformSizes

export const styleOptions = [
  { value: "motivational", label: "Motivational" },
  { value: "business", label: "Business" },
  { value: "educational", label: "Educational" },
  { value: "humorous", label: "Humorous" },
  { value: "inspirational", label: "Inspirational" },
  { value: "promotional", label: "Promotional" },
]

export const toneOptions = [
  { value: "professional", label: "Professional" },
  { value: "casual", label: "Casual" },
  { value: "friendly", label: "Friendly" },
  { value: "authoritative", label: "Authoritative" },
  { value: "playful", label: "Playful" },
]

export const templateCategories = [
  { id: "all", label: "All Templates" },
  { id: "neon", label: "Neon" },
  { id: "elegant", label: "Elegant" },
  { id: "quote", label: "Quotes" },
  { id: "marketing", label: "Marketing" },
  { id: "educational", label: "Educational" },
  { id: "minimal", label: "Minimal" },
  { id: "colorful", label: "Colorful" },
  { id: "corporate", label: "Corporate" },
]
