export interface Template {
  id: string
  name: string
  category: "quote" | "marketing" | "educational" | "minimal" | "colorful" | "corporate" | "neon" | "elegant"
  backgroundType: "gradient" | "solid"
  gradient?: string
  backgroundColor?: string
  borderColor?: string
  borderWidth?: number
  textColor: string
  accentColor?: string
  fontFamily: string
  fontWeight?: number
  fontSize: number
  textAlign: "left" | "center" | "right"
  padding: number
  preview?: string
  isPremium?: boolean
}

export const templates: Template[] = [
  {
    id: "visionary-1",
    name: "Visionary Neon",
    category: "neon",
    backgroundType: "solid",
    backgroundColor: "#0A1A2F",
    borderColor: "#0FB4FF",
    borderWidth: 4,
    textColor: "#ffffff",
    accentColor: "#0FB4FF",
    fontFamily: "Inter",
    fontWeight: 300,
    fontSize: 32,
    textAlign: "center",
    padding: 50,
    preview: "On ne change pas un pays avec du bruit. On le change avec des systèmes.",
  },
  {
    id: "visionary-2",
    name: "Neon Purple",
    category: "neon",
    backgroundType: "solid",
    backgroundColor: "#1A0A2F",
    borderColor: "#A855F7",
    borderWidth: 4,
    textColor: "#ffffff",
    accentColor: "#A855F7",
    fontFamily: "Inter",
    fontWeight: 300,
    fontSize: 32,
    textAlign: "center",
    padding: 50,
    preview: "Innovation distinguishes between a leader and a follower.",
    isPremium: true,
  },
  {
    id: "visionary-3",
    name: "Neon Green",
    category: "neon",
    backgroundType: "solid",
    backgroundColor: "#0A1F1A",
    borderColor: "#10B981",
    borderWidth: 4,
    textColor: "#ffffff",
    accentColor: "#10B981",
    fontFamily: "Inter",
    fontWeight: 300,
    fontSize: 32,
    textAlign: "center",
    padding: 50,
    preview: "The future belongs to those who believe.",
  },
  {
    id: "visionary-4",
    name: "Neon Red",
    category: "neon",
    backgroundType: "solid",
    backgroundColor: "#1F0A0A",
    borderColor: "#EF4444",
    borderWidth: 4,
    textColor: "#ffffff",
    accentColor: "#EF4444",
    fontFamily: "Inter",
    fontWeight: 300,
    fontSize: 32,
    textAlign: "center",
    padding: 50,
    preview: "Action is the foundational key to all success.",
    isPremium: true,
  },
  {
    id: "elegant-1",
    name: "Elegant Black",
    category: "elegant",
    backgroundType: "solid",
    backgroundColor: "#000000",
    borderColor: "#D4AF37",
    borderWidth: 3,
    textColor: "#ffffff",
    accentColor: "#D4AF37",
    fontFamily: "Playfair Display",
    fontWeight: 400,
    fontSize: 30,
    textAlign: "center",
    padding: 60,
    preview: "Excellence is not a destination but a continuous journey.",
    isPremium: true,
  },
  {
    id: "elegant-2",
    name: "Elegant White",
    category: "elegant",
    backgroundType: "solid",
    backgroundColor: "#FAFAFA",
    borderColor: "#1F2937",
    borderWidth: 2,
    textColor: "#1F2937",
    accentColor: "#6B7280",
    fontFamily: "Playfair Display",
    fontWeight: 400,
    fontSize: 30,
    textAlign: "center",
    padding: 60,
    preview: "Simplicity is the ultimate sophistication.",
  },
  // Original gradient templates with updated interface
  {
    id: "motivational-1",
    name: "Motivational Gradient",
    category: "quote",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    textColor: "#ffffff",
    fontFamily: "Playfair Display",
    fontSize: 32,
    textAlign: "center",
    padding: 40,
    preview: "Dream big, start small, act now.",
  },
  {
    id: "business-1",
    name: "Business Blue",
    category: "marketing",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 28,
    textAlign: "center",
    padding: 40,
    preview: "Grow your business today",
  },
  {
    id: "education-1",
    name: "Education Teal",
    category: "educational",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #0d9488 0%, #14b8a6 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 26,
    textAlign: "left",
    padding: 40,
    preview: "Did you know?",
  },
  {
    id: "minimal-1",
    name: "Minimal Dark",
    category: "minimal",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #1f2937 0%, #111827 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 28,
    textAlign: "center",
    padding: 50,
    preview: "Less is more.",
  },
  {
    id: "colorful-1",
    name: "Sunset Vibes",
    category: "colorful",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #f97316 0%, #ec4899 100%)",
    textColor: "#ffffff",
    fontFamily: "Poppins",
    fontSize: 30,
    textAlign: "center",
    padding: 40,
    preview: "Make it pop!",
  },
  {
    id: "corporate-1",
    name: "Corporate Gray",
    category: "corporate",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #374151 0%, #4b5563 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 26,
    textAlign: "left",
    padding: 40,
    preview: "Professional Excellence",
  },
  {
    id: "quote-2",
    name: "Ocean Blue",
    category: "quote",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #0ea5e9 0%, #2dd4bf 100%)",
    textColor: "#ffffff",
    fontFamily: "Playfair Display",
    fontSize: 30,
    textAlign: "center",
    padding: 45,
    preview: "Stay focused, stay positive",
  },
  {
    id: "marketing-2",
    name: "Bold Red",
    category: "marketing",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #dc2626 0%, #f97316 100%)",
    textColor: "#ffffff",
    fontFamily: "Poppins",
    fontSize: 32,
    textAlign: "center",
    padding: 35,
    preview: "Limited Time Offer!",
  },
  {
    id: "quote-3",
    name: "Royal Purple",
    category: "quote",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #c026d3 100%)",
    textColor: "#ffffff",
    fontFamily: "Playfair Display",
    fontSize: 32,
    textAlign: "center",
    padding: 45,
    preview: "Believe in yourself",
    isPremium: true,
  },
  {
    id: "minimal-2",
    name: "Pure White",
    category: "minimal",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #ffffff 0%, #f3f4f6 100%)",
    textColor: "#111827",
    fontFamily: "Inter",
    fontSize: 28,
    textAlign: "center",
    padding: 50,
    preview: "Simplicity wins.",
  },
  {
    id: "colorful-2",
    name: "Neon Pop",
    category: "colorful",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #06b6d4 0%, #8b5cf6 100%)",
    textColor: "#ffffff",
    fontFamily: "Poppins",
    fontSize: 30,
    textAlign: "center",
    padding: 40,
    preview: "Stand out!",
    isPremium: true,
  },
  {
    id: "educational-2",
    name: "Fresh Green",
    category: "educational",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #22c55e 0%, #16a34a 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 26,
    textAlign: "center",
    padding: 40,
    preview: "Learn something new",
  },
  {
    id: "marketing-3",
    name: "Golden Hour",
    category: "marketing",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #fbbf24 0%, #f97316 100%)",
    textColor: "#1f2937",
    fontFamily: "Poppins",
    fontSize: 30,
    textAlign: "center",
    padding: 40,
    preview: "Exclusive Deal",
    isPremium: true,
  },
  {
    id: "corporate-2",
    name: "Navy Pro",
    category: "corporate",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #1e3a8a 0%, #1e40af 100%)",
    textColor: "#ffffff",
    fontFamily: "Inter",
    fontSize: 26,
    textAlign: "center",
    padding: 40,
    preview: "Leading the way",
  },
  {
    id: "quote-4",
    name: "Warm Blush",
    category: "quote",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #fda4af 0%, #fb7185 100%)",
    textColor: "#1f2937",
    fontFamily: "Playfair Display",
    fontSize: 30,
    textAlign: "center",
    padding: 45,
    preview: "Love what you do",
  },
  {
    id: "minimal-3",
    name: "Soft Gray",
    category: "minimal",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #e5e7eb 0%, #d1d5db 100%)",
    textColor: "#374151",
    fontFamily: "Inter",
    fontSize: 28,
    textAlign: "center",
    padding: 50,
    preview: "Keep it simple",
  },
  {
    id: "marketing-4",
    name: "Aqua Pulse",
    category: "marketing",
    backgroundType: "gradient",
    gradient: "linear-gradient(140deg, #0ea5e9 0%, #22d3ee 40%, #f59e0b 100%)",
    textColor: "#0b1220",
    fontFamily: "Poppins",
    fontSize: 30,
    textAlign: "center",
    padding: 42,
    preview: "Lancement express -40%",
    isPremium: true,
  },
  {
    id: "corporate-3",
    name: "Steel Focus",
    category: "corporate",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #0f172a 0%, #1f2937 50%, #0ea5e9 100%)",
    textColor: "#e5e7eb",
    fontFamily: "Inter",
    fontSize: 27,
    textAlign: "left",
    padding: 48,
    preview: "Quarterly results +12%",
  },
  {
    id: "quote-5",
    name: "Noir Chic",
    category: "quote",
    backgroundType: "solid",
    backgroundColor: "#0b0c10",
    borderColor: "#f59e0b",
    borderWidth: 3,
    textColor: "#f8fafc",
    accentColor: "#f59e0b",
    fontFamily: "Playfair Display",
    fontWeight: 500,
    fontSize: 32,
    textAlign: "center",
    padding: 52,
    preview: "Créer aujourd'hui, inspirer demain.",
    isPremium: true,
  },
  {
    id: "colorful-3",
    name: "Neon Wave",
    category: "colorful",
    backgroundType: "gradient",
    gradient: "linear-gradient(125deg, #7c3aed 0%, #22d3ee 40%, #f97316 100%)",
    textColor: "#fdfdfd",
    fontFamily: "Poppins",
    fontSize: 30,
    textAlign: "center",
    padding: 44,
    preview: "Drop de collection",
  },
  {
    id: "minimal-4",
    name: "Sand Stone",
    category: "minimal",
    backgroundType: "solid",
    backgroundColor: "#f8f5ef",
    borderColor: "#d6c6a1",
    borderWidth: 2,
    textColor: "#3f3a2f",
    accentColor: "#d6c6a1",
    fontFamily: "Inter",
    fontSize: 28,
    textAlign: "center",
    padding: 56,
    preview: "Clarté. Calme. Impact.",
  },
  {
    id: "elegant-3",
    name: "Velvet Gold",
    category: "elegant",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #0f0f14 0%, #1c1b23 60%, #cfa25a 100%)",
    textColor: "#f5e9d7",
    fontFamily: "Playfair Display",
    fontWeight: 500,
    fontSize: 30,
    textAlign: "center",
    padding: 58,
    preview: "Chaque détail compte.",
    isPremium: true,
  },
  {
    id: "educational-3",
    name: "Blueprint",
    category: "educational",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #0b1021 0%, #0f172a 40%, #3b82f6 100%)",
    textColor: "#e2e8f0",
    fontFamily: "Inter",
    fontSize: 26,
    textAlign: "left",
    padding: 46,
    preview: "3 clés pour mieux apprendre",
  },
  {
    id: "neon-5",
    name: "Cyber Lime",
    category: "neon",
    backgroundType: "solid",
    backgroundColor: "#07130f",
    borderColor: "#8bffb3",
    borderWidth: 4,
    textColor: "#e2fff0",
    accentColor: "#8bffb3",
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: 31,
    textAlign: "center",
    padding: 50,
    preview: "Make it unforgettable.",
  },
  {
    id: "marketing-5",
    name: "Gradient Surge",
    category: "marketing",
    backgroundType: "gradient",
    gradient: "linear-gradient(130deg, #f59e0b 0%, #0ea5e9 50%, #7c3aed 100%)",
    textColor: "#0f172a",
    fontFamily: "Poppins",
    fontSize: 30,
    textAlign: "center",
    padding: 42,
    preview: "Nouvelle collection en live",
  },
  {
    id: "marketing-6",
    name: "Edge Contrast",
    category: "marketing",
    backgroundType: "solid",
    backgroundColor: "#0f172a",
    borderColor: "#22d3ee",
    borderWidth: 3,
    textColor: "#e2e8f0",
    accentColor: "#22d3ee",
    fontFamily: "Inter",
    fontWeight: 600,
    fontSize: 28,
    textAlign: "left",
    padding: 48,
    preview: "Lancement produit + bonus",
  },
  {
    id: "quote-6",
    name: "Serif Glow",
    category: "quote",
    backgroundType: "gradient",
    gradient: "linear-gradient(180deg, #0b1021 0%, #1f2937 60%, #111827 100%)",
    textColor: "#f8fafc",
    accentColor: "#f59e0b",
    fontFamily: "Playfair Display",
    fontWeight: 500,
    fontSize: 34,
    textAlign: "center",
    padding: 58,
    preview: "Rêver, bâtir, partager.",
    isPremium: true,
  },
  {
    id: "quote-7",
    name: "Pastel Calm",
    category: "quote",
    backgroundType: "solid",
    backgroundColor: "#f3f4f6",
    textColor: "#1f2937",
    accentColor: "#0ea5e9",
    fontFamily: "Playfair Display",
    fontWeight: 500,
    fontSize: 30,
    textAlign: "center",
    padding: 60,
    preview: "Petit pas, grand impact.",
  },
  {
    id: "corporate-4",
    name: "Slate Focus",
    category: "corporate",
    backgroundType: "solid",
    backgroundColor: "#0f172a",
    borderColor: "#334155",
    borderWidth: 2,
    textColor: "#e2e8f0",
    accentColor: "#38bdf8",
    fontFamily: "Inter",
    fontWeight: 500,
    fontSize: 26,
    textAlign: "left",
    padding: 50,
    preview: "Roadmap Q3",
  },
  {
    id: "minimal-5",
    name: "Ivory Grid",
    category: "minimal",
    backgroundType: "solid",
    backgroundColor: "#fdfbf5",
    borderColor: "#e4e1d0",
    borderWidth: 2,
    textColor: "#1f2937",
    accentColor: "#94a3b8",
    fontFamily: "Inter",
    fontWeight: 500,
    fontSize: 28,
    textAlign: "center",
    padding: 48,
    preview: "Design clean & focus",
  },
  {
    id: "colorful-4",
    name: "Candy Pop",
    category: "colorful",
    backgroundType: "gradient",
    gradient: "linear-gradient(120deg, #ec4899 0%, #f97316 45%, #22d3ee 100%)",
    textColor: "#0f172a",
    fontFamily: "Poppins",
    fontSize: 30,
    textAlign: "center",
    padding: 42,
    preview: "Flash sale 24h",
    isPremium: true,
  },
  {
    id: "educational-4",
    name: "Notebook",
    category: "educational",
    backgroundType: "gradient",
    gradient: "linear-gradient(135deg, #0f172a 0%, #0ea5e9 40%, #22d3ee 100%)",
    textColor: "#e2e8f0",
    fontFamily: "Inter",
    fontSize: 24,
    textAlign: "left",
    padding: 46,
    preview: "3 points clés à retenir",
  },
  {
    id: "neon-6",
    name: "Violet Pulse",
    category: "neon",
    backgroundType: "gradient",
    gradient: "linear-gradient(145deg, #0b0f1a 0%, #111827 50%, #8b5cf6 100%)",
    textColor: "#ede9fe",
    accentColor: "#c084fc",
    fontFamily: "Inter",
    fontWeight: 500,
    fontSize: 32,
    textAlign: "center",
    padding: 52,
    preview: "Stay bold. Stay bright.",
  },
  {
    id: "elegant-4",
    name: "Marble Luxe",
    category: "elegant",
    backgroundType: "solid",
    backgroundColor: "#f5f1ea",
    borderColor: "#c7b299",
    borderWidth: 2,
    textColor: "#1f2937",
    accentColor: "#c08457",
    fontFamily: "Playfair Display",
    fontWeight: 500,
    fontSize: 31,
    textAlign: "center",
    padding: 60,
    preview: "La forme suit le sens.",
    isPremium: true,
  },
  {
    id: "marketing-7",
    name: "Bold Split",
    category: "marketing",
    backgroundType: "gradient",
    gradient: "linear-gradient(90deg, #0f172a 0%, #0ea5e9 50%, #0f172a 100%)",
    textColor: "#e2e8f0",
    fontFamily: "Poppins",
    fontSize: 29,
    textAlign: "left",
    padding: 44,
    preview: "Offre limitée ce week-end",
  },
]

export const platformSizes = {
  "instagram-square": { width: 1080, height: 1080, label: "Instagram Post" },
  "instagram-story": { width: 1080, height: 1920, label: "Instagram Story" },
  tiktok: { width: 1080, height: 1920, label: "TikTok" },
  facebook: { width: 1200, height: 630, label: "Facebook Post" },
  twitter: { width: 1200, height: 675, label: "X/Twitter" },
  linkedin: { width: 1200, height: 627, label: "LinkedIn" },
}

export type PlatformKey = keyof typeof platformSizes

export const styleOptions = [
  { value: "motivational", label: "Motivational" },
  { value: "business", label: "Business" },
  { value: "educational", label: "Educational" },
  { value: "humorous", label: "Humorous" },
  { value: "inspirational", label: "Inspirational" },
  { value: "promotional", label: "Promotional" },
]

export const toneOptions = [
  { value: "professional", label: "Professional" },
  { value: "casual", label: "Casual" },
  { value: "friendly", label: "Friendly" },
  { value: "authoritative", label: "Authoritative" },
  { value: "playful", label: "Playful" },
]

export const templateCategories = [
  { id: "all", label: "All Templates" },
  { id: "neon", label: "Neon" },
  { id: "elegant", label: "Elegant" },
  { id: "quote", label: "Quotes" },
  { id: "marketing", label: "Marketing" },
  { id: "educational", label: "Educational" },
  { id: "minimal", label: "Minimal" },
  { id: "colorful", label: "Colorful" },
  { id: "corporate", label: "Corporate" },
]
